imply:
  container_name: imply-quickstart-druid
  image: aviata/imply-quickstart
  expose:
    - "8081" # Coordinator
    - "8082" # Broker
    - "8083" # Historical
    - "8084" # Overlord
    - "8085" # Middle Manager
    - "8090" # Indexing Service
  ports:
    - "9095:9095" # Bard
panoramix:
  container_name: imply-quickstart-panoramix
  image: aviata/panoramix
  links:
    - imply:druid
  ports:
    - "8088:8088" # Web UI

